### ISSUE TITLE
LinguisticAbility - Definition?

### ISSUE THREAD

**Issue by rwarren2** [rwarren2/cwrc#2]
@lemaka @colinraybrian Please look into whether LinguisticAbility should be  verbal or written.

**Comment by SusanBrown** [comment]
In our documentation it is defined as either or both.

On Oct 17, 2016, at 9:41 PM, rwarren2 <notifications@github.com<mailto:notifications@github.com>> wrote:


@lemaka<https://github.com/lemaka> @colinraybrian<https://github.com/colinraybrian> Please look into whether LinguisticAbility should be verbal or written.

**Comment by rwarren2** [comment]
Done.
