### ISSUE TITLE
NationalityContext versus NationalHeritage / NationalIdentity

### ISSUE THREAD

**Issue by rwarren2** [rwarren2/cwrc#4]
Which of NationalHeritage or NationalIdentity should NationalityContext be the subject of? Both?

**Comment by SusanBrown** [comment]
Both, also GeographicalHeritage should be grouped with them.

On Oct 17, 2016, at 9:56 PM, rwarren2 <notifications@github.com<mailto:notifications@github.com>> wrote:


Which of NationalHeritage or NationalIdentity should NationalityContext be the subject of? Both?

**Comment by rwarren2** [comment]
Done.
